@startuml
title: QCoDeS Components

[Station] as station
[Instrument] as instrument
() snapshot
() device

snapshot <. station: outputs
instrument <-> device: communicates

station <-- instrument

@enduml