@startuml

!includesub ERD_head.puml!HEAD
!includesub ERD_head.puml!KEYS

!includesub ERD_fab.puml!FAB

!includesub ERD_measurement.puml!MEASUREMENT
!includesub ERD_measurement.puml!ANALYSIS



' Relationship symbols:

' Type	        Symbol
' Zero or One	|o--
' Exactly One	||--
' Zero or Many	}o--
' One or Many	}|--

meas::device_id }|--|| device::ID : measured >

@enduml
