@startuml

!startsub KEYS

!define PK <size:12><&key></size><b>
!define FK <size:12><&link-intact></size><i>

!endsub

!startsub HEAD

left to right direction
hide circle
'skinparam linetype ortho

!endsub

@enduml
