"""
This test was generated by an LLM.

It does not test actual functionality. It just tests that the module device_GUI.py can be imported and that some code
paths don't raise an exception.
"""

import multiprocessing as mp
import types

import pytest
from qtpy.QtCore import QObject, Qt
from qtpy.QtCore import Signal as pyqtSignal

import qumada.utils.device_GUI as device_GUI


class DummyWorker(QObject):
    """Deterministic replacement for device_GUI.Worker used in most tests."""

    data_ready = pyqtSignal(list)

    def __init__(self, interval, parameters):
        super().__init__()
        self.interval = interval
        self.parameters = parameters
        self.running = True

    def stop(self):
        self.running = False


@pytest.fixture
def parameters():
    p1 = device_GUI.Parent("P1")
    p2 = device_GUI.Parent("P2")
    return [
        device_GUI.Parameter("A", p1),
        device_GUI.Parameter("B", p1),
        device_GUI.Parameter("C", p2),
    ]


@pytest.fixture
def gui(qtbot, parameters, monkeypatch):
    # Replace Worker with a deterministic stub
    monkeypatch.setattr(device_GUI, "Worker", DummyWorker)
    q = mp.Queue()
    w = device_GUI.MeasurementGUI(parameters, q)
    qtbot.addWidget(w)
    # keep intervals small if anything uses it
    w.interval_spinbox.setValue(120)
    return w


def _col_texts(table, col):
    return [(table.item(r, col).text() if table.item(r, col) is not None else "") for r in range(table.rowCount())]


def test_initial_table_population(gui, parameters):
    assert gui.table.rowCount() == len(parameters)
    # Column 0: names "Param: <parent> <name>"
    names = _col_texts(gui.table, 0)
    assert names == [f"Param: {p._parent.name} {p.name}" for p in parameters]
    # Column 1: initial values from __call__() -> "42"
    values = _col_texts(gui.table, 1)
    assert values == ["42"] * len(parameters)


def test_update_interval_changes_worker_field(gui, qtbot):
    # Initial value is 120 from fixture
    assert gui.worker.interval == 120
    gui.interval_spinbox.setValue(333)
    # Signal is connected in initUI; the slot sets worker.interval
    assert gui.worker.interval == 333


def test_close_event_stops_worker_and_puts_quit(gui, qtbot):
    q = gui.data_queue
    # Thread should be running before close
    assert gui.worker_thread.isRunning()
    gui.close()

    # After close, thread should be stopped
    assert not gui.worker_thread.isRunning()
    # Worker stop() should have been called
    assert gui.worker.running is False
    # Queue should receive "QUIT"
    assert q.get(timeout=1) == "QUIT"
