variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip


stages:
  - test
  - deploy


.base:
  image: python:3.11
  before_script:
    - pip install -U virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - echo "machine git-ce.rwth-aachen.de" > ~/.netrc
    - echo "login gitlab-ci-token" >> ~/.netrc
    - echo "password ${CI_JOB_TOKEN}" >> ~/.netrc


.tox:
  extends:
    - .base
  before_script:
    - !reference [.base, before_script]
    - pip install tox


.test:
  extends:
    - .tox
  stage: test
  before_script:
    - apt-get update && apt-get install -y xvfb libegl1 libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 x11-utils libxcb-cursor0
    - !reference [.tox, before_script]
  coverage: /^TOTAL.+?(\d+%)$/
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml


pylint:
  extends:
    - .tox
  stage: test
  allow_failure: true
  script:
    - tox -e lint -- --exit-zero --load-plugins=pylint_gitlab --output-format=gitlab-codeclimate:codeclimate.json
  artifacts:
    when: always
    reports:
      codequality: codeclimate.json


py39:
  extends:
    - .test
  image: python:3.9
  script:
    - tox -e py39 -- --junitxml=report.xml --cov-report xml


py310:
  extends:
    - .test
  image: python:3.10
  script:
    - tox -e py310 -- --junitxml=report.xml --cov-report xml


py311:
  extends:
    - .test
  image: python:3.11
  script:
    - tox -e py311 -- --junitxml=report.xml --cov-report xml


pages:
  extends:
    - .base
  stage: deploy
  script:
    - pip install sphinx sphinx_autodoc_typehints sphinx_autopackagesummary sphinx_rtd_theme
    - pip install -e .
    - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
    - main
